tutorialdjango/blog/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views
from .views import *

app_name = "blog"

urlpatterns = [
    path('', views.PostListView.as_view(), name="list"),
    path('create/', views.PostCreateView.as_view(), name="create"),
    path('<slug:slug>/', views.PostDetailView.as_view(), name="detail"),
    path('<slug:slug>/update/', views.PostUpdateView.as_view(), name="update"),
    path('<slug:slug>/delete/', views.PostDeleteView.as_view(), name="delete"),

    # path('home/', views.index, name="home"),
    # path('', views.HomePageView.as_view(), name="home"),
    # template_name="blog/post_create.html"
    # path('create/', views.PostCreateView.as_view(), name='create'),
    # path('<slug:slug>/<int:pk>/', views.CreateView.as_view(), name="create"),
    # path('<slug:slug>/<int:pk>/delete', views.DeleteView.as_view(), name="delete"),
    # path('<slug:slug>/edit', views.PostDetailView.as_view(), name="edit"),
]

tutorialdjango/tutorialdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls", namespace="blog")),
    path('accounts/', include('allauth.urls')),
]

tutorialdjango/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from .utils import unique_slug_generator
from django.db.models.signals import pre_save

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})
    
    class Meta:
        ordering = ("-created",)

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
        # instance.slug = unique_slug_generator(instance)

# def pre_save_post_receiver(sender, instance, *args, **kwargs):
#     slug = slugify(instance.title)
#     exists = Post.objects.filter(slug=slug).exists()
#     if exists:
#         slug = "%s-%s" %(slug, instance.id)
#     instance.slug = slug
#     # if not instance.slug:
#     #     # instance.slug = create_slug(instance)
#     #     instance.slug = unique_slug_generator(instance)

pre_save.connect(pre_save_post_receiver, sender=Post)

tutorialdjango/blog/forms.py
from blog.models import Post
from django.forms import ModelForm

class PostModelForm(ModelForm):
    class Meta:
        model = Post
        fields =  ['title', 'slug', 'author','body']
        prepopulated_fields = {"slug": ("title",)}

tutorialdjango/blog/views.py
from django.http.response import HttpResponseRedirect
from blog.forms import PostModelForm
from django.shortcuts import render
from django.views.generic import DetailView, ListView, TemplateView, CreateView, UpdateView, DeleteView
from .models import Post
from django.urls import reverse_lazy
from django.shortcuts import render,  redirect

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


# Create your views here.

class PostListView(ListView):
    model = Post

class PostDetailView(DetailView):
    model = Post
    

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(UpdateView):
    model = Post
    fields = ['title', 'body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        if self.request.user != post.author:
            if self.request.user == 'admin':
                return True
        return False

class PostDeleteView(DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        if self.request.user != post.author:
            if self.request.user == 'admin':
                return True
        
        return False

tutorialdjango/blog/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Django{% block title%}{% endblock title%}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<style>
    body {
        background-color: #2a74d6;
    }
</style>

<body>
    <!-- <p id="notice"></p> -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

            <a class="navbar-brand" href="/">Blog Django</a> 
            {% comment %} {% block hello %}  {% endcomment %}
                {% if user.is_authenticated %}
                    <p style="color: white;">Ola {{ user.username }}</p>
                {% endif %} 
            {% comment %} {% endblock hello %} {% endcomment %}
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0"></ul>

            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                </li>
                {% endif %}
            </ul>

        </div>
    </nav>

    <br>
    <br>

    <div class="container">
        <div class="jumbotron">
            <header>
                <h1>Blog Principal</h1>
                <br>
            </header>

            <main>
                {% block content %} {% endblock content%}
            </main>

        </div>
    </div>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>


    <footer class="footer">
        <div class="container">
            <span style="color: white"> Aplicação criada utilizando framework Django - Josué Lopes - Copyright 2021</span>
        </div>
    </footer>
</body>


</html>

tutorialdjango/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>

<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{% endblock title%}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


</head>

<body>
    <p id="notice"></p>

    <div class="container">
        <div class="jumbotron">
            <header>
                <h1>Blog Principal</h1>
                <br>
            </header>

            <main>
                {% block content %} {% endblock content%}
            </main>
        </div>
    </div>


</body>

</html>

tutorialdjango/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %} 

{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Deletar Post</legend>
            <h2>Tem certeza que deseja deletar esse post ?</h2>
            <h4 align="left">"{{ object.title }}"</h4>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Sim, Apague</button>
            <a class="btn btn-outline-secondary" href="{% url 'blog:list' %}">Cancelar</a>
        </div>
    </form>
</div>
{% endblock content %}

tutorialdjango/blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block title %} - {{ post.title }}{% endblock title %}

{% block hello %}
    {% if user.is_authenticated %}
        <p>Ola {{ user.username }}</p>
    {% endif %}
{% endblock hello %}

{% block content %}
    <h2>{{ post.title }}</h2>
    <p class="date">
        Publicado em {{ post.created }} por {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <a href="{% url 'blog:list' %}" class="btn btn-info">Voltar</a>

    {% if user.is_authenticated %}

        {% if object.author == user %}
            {% if user.username != 'admin' %}
                <a href="{% url 'blog:update' post.slug %}" class="btn btn-info">Editar</a>
                <a href="{% url 'blog:delete' post.slug %}" class="btn btn-info">Apagar</a>
            {% endif %}
            {% if user.username == 'admin' %}
                <a href="{% url 'blog:update' post.slug %}" class="btn btn-info">Editar</a>
                <a href="{% url 'blog:delete' post.slug %}" class="btn btn-info">Apagar</a>
            {% endif %}
        {% endif %}

        {% if object.author != user %}
            {% if user.username == 'admin' %}
                <a href="{% url 'blog:update' post.slug %}" class="btn btn-info">Editar</a>
                <a href="{% url 'blog:delete' post.slug %}" class="btn btn-info">Apagar</a>
            {% endif %}
        {% endif %}

    {% endif %}
{% endblock content %}

tutorialdjango/blog/templates/blog/post_form.html
{% extends "base.html" %} 
{% load crispy_forms_tags %} 

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-info" type="submit">Post</button>
                <a href="{% url 'blog:list' %}" class="btn btn-info">Voltar</a>
            </div>
        </form>
    </div>
{% endblock content %}

tutorialdjango/blog/templates/blog/post_list.html
{% extends "base.html" %} 

{% block title %} - Meu Bloco{% endblock title %} 

{% block content %} 

    {% for post in post_list %}
        <article>
            <h2>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h2>

            <p class="date">
                Publicado em {{ post.created }} por {{ post.author }}
            </p>

            {{ post.body|linebreaks|truncatewords:10 }}
        </article>
    {% endfor %} 

    {% if user.is_authenticated %}
        <br>
        <a href="{% url 'blog:create' %}" class="btn btn-info">Novo Artigo</a> 
    {% endif %} 

{% endblock content %}

tutorialdjango/tutorialdjango/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{% endblock title%}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <!-- <p id="notice"></p> -->

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="#">Blog Django</a>
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <!-- <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li> -->
            </ul>

            <!-- <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form> -->

            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                </li>
                {% endif %}
            </ul>

        </div>
    </nav>

    <br>
    <br>

    <div class="container">
        <div class="jumbotron">
            <header>
                <h1>Blog Principal</h1>
                <br>
            </header>

            <main>
                {% block content %} {% endblock content%}
            </main>
        </div>
    </div>


</body>

</html>

tutorialdjango/tutorialdjango/templates/home.html
{% extends 'base.html' %}

{% block title %}Loja Python{% endblock %}

{% block content %}
    Olá!
{% endblock %}